apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.Name | default .Chart.Name }}-job
  labels:
    app: {{ .Values.Name | default .Chart.Name }}-job
    chart: {{ .Values.Name | default .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}  
spec:
  schedule: "{{ .Values.cronJobSchedule }}"
  suspend: {{ .Values.cronJobSuspended }}
  jobTemplate:
    spec:
      concurrencyPolicy: Forbid
      template:
        spec:
          containers:
          - name: {{ .Values.Name | default .Chart.Name }}-job
            image: busybox:1.30.1
            args:
            - /bin/sh
            - -ec
            - "/bin/wget --post-data='' -S -O - http://{{ .Values.Name | default .Chart.Name }}/v1/Trigger/Pull"
          restartPolicy: Never