apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.Name | default .Chart.Name }}-cronjob
spec:
  schedule: "{{ .Values.cronJobSchedule }}"
  jobTemplate:
    spec:
      concurrencyPolicy: Forbid
      successfulJobsHistoryLimit: 1
      failedJobsHistoryLimit: 1
      template:
        spec:
          containers:
          - name: {{ .Values.Name | default .Chart.Name }}-cronjob
            image: byrnedo/alpine-curl:0.1.7
            args:
            - /bin/sh
            - -c
            - curl
            - -s
            - -X
            - POST
            - http://{{ .Values.Name | default .Chart.Name }}/v1/Trigger/Pull
          restartPolicy: Never
