language: csharp
dist: xenial
dotnet: 2.2
# mono: none

install: 
- bash ./cicd.sh install

script:
- bash ./cicd.sh build

deploy:
  provider: script
  #skip_cleanup: true
  script: bash ./cicd.sh deploy
  on:
    branch: release  
    tags: true
