parentDomain: {{k8sParentDomain}}
replicaCount: 1
image:
  repository: {{dockerHubUser}}/{{helmChartName}}
  tag: 0
dockerRegistrationSecret: ole-docker-reg

# Runtime
ASPNETCORE_ENVIRONMENT: "Development"
TZ: "America/Sao_Paulo"

# Log
Serilog__MinimumLevel__Default: Warning
Serilog__MinimumLevel__Override__Ole: Information
Serilog__MinimumLevel__Override__Otc: Information
RequestTrackerConfiguration__RequestTrackerEnabled: "true"

# Core
# variaveis de ambiente que afetam comportamentos de negocio

# Servicos externos
# apontamentos para servicos hospedados fora do kubernetes
# WSAutorizador: "http://wsautorizador.oleconsignado.com.br/"

# DB
# strings de conexao com banco de dados

# Cache
DistributedCacheConfiguration__CacheStorageType: "SqlServer"
DistributedCacheConfiguration__CacheSqlConnectionString: "{{cacheSqlConnectionString}};Application Name={{helmChartName}};"
DistributedCacheConfiguration__CacheSqlSchemaName: "dbo"
DistributedCacheConfiguration__CacheSqlTableName: "{{cacheTable}}"

# Jwt
JwtConfiguration__Audience: "{{helmChartName}}"
JwtConfiguration__Issuer: "{{helmChartName}}"
JwtConfiguration__SecretKey: "{{uniqueIdentifier}}"

# Recursos
memoryRequest: "256Mi"
cpuRequest: "100m"
memoryLimit: "384Mi"
cpuLimit: "400m"

#
# Configuracoes que afetam o comportamento do WebHostedWorker
#

# -- WorkerTimeoutInSeconds --
#
#    Tempo maximo permitido para um trabalho (IHostedWorker.WorkAsync) executar.
#    Apos WorkerTimeoutInSeconds, sera solicitado encerramento por meio do cancelationToken.
#
#    Valor padrao: 60
HostedWorkerConfiguration__WorkerTimeoutInSeconds: "60"

# -- WorkerTerminationTorerationTimeoutInSeconds --
#
#    Caso o WorkerTimeoutInSeconds seja atingido, apos solicitar o encerramento por meio do
#    cancelationToken, caso o trabalho nao termine em mais
#    WorkerTerminationTorerationTimeoutInSeconds, a aplicacao como um todo sera encerrada.
#
#    Valor padrao: 15
HostedWorkerConfiguration__WorkerTerminationTorerationTimeoutInSeconds: "15"

# -- MaxConsecutiveErrors --
#
#    Quantidade maxima de erros consecutivos permitidos. Apos atigir MaxConsecutiveErrors
#    erros consecutivos, a aplicacao sera encerrada.
#
#    Valor padrao: 5
HostedWorkerConfiguration__MaxConsecutiveErrors: "5"

# WebHostedWorker Schedule
#
#                  +---------------- minute (0 - 59)
#                  |    +------------- hour (0 - 23)
#                  |    |    +---------- day of month (1 - 31)
#                  |    |    |    +------- month (1 - 12)
#                  |    |    |    |    +---- day of week (0 - 6) (Sunday=0 or 7)
#                  |    |    |    |    | 
cronJobSchedule: "*/15  *    *    *    *"

# Suspend the cronJob to start
#
#    If false, the cronjob is actively scheduling job, if true existing job will not be forced 
#    to terminate but new ones cannot be scheduled;
cronJobSuspended: "false"
